spring:
  application:
    name: ${blog-api.application.name}
  datasource:
    url: ${blog-api.datasource.url}
    username: ${blog-api.datasource.username}
    password: ${blog-api.datasource.password}
    
mybatis:
  type-aliases-package: ${blog-api.mybatis.type-aliases-package}
  #mapperLocations: classpath:mapper/*.xml
  configuration:
   map-underscore-to-camel-case: true
server:
  port: ${blog-api.server.port}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${blog-api.service-url.defaultZone}