server:
  port: ${blog-user.server.port}

spring:
  datasource:
    url: ${blog-user.datasource.url}
    username: ${blog-user.datasource.username}
    password: ${blog-user.datasource.password}
  application:
    name: ${blog-user.application.name} # 应用名称
mybatis:
  type-aliases-package: ${blog-user.mybatis.type-aliases-package}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${blog-gateway.service-url.defaultZone}