spring:
  application:
    name: ${blog-service.application.name}
  datasource:
    url: ${blog-service.datasource.url}
    username: ${blog-service.datasource.username}
    password: ${blog-service.datasource.password}
    
mybatis:
  type-aliases-package: ${blog-service.mybatis.type-aliases-package}
  
server:
  port: ${blog-service.server.port}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${blog-service.service-url.defaultZone}