server:
  port: ${blog-test.server.port} # 端口
spring:
  application:
    name: ${blog-test.application.name} # 应用名称，会在Eureka中显示
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${blog-test.service-url.defaultZone}