spring:
  application:
    name: ${blog-gateway.application.name}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ${blog-gateway.routes.id1}
        uri: ${blog-gateway.routes.uri1}
        predicates:
          ${blog-gateway.routes.predicates1}
      - id: ${blog-gateway.routes.id2}
        uri: ${blog-gateway.routes.uri2}
        predicates:
          ${blog-gateway.routes.predicates2}
#      - id: host_route
#        uri: lb://manage
#        predicates:
#        - Path=/manage/**


server:
  port: ${blog-gateway.server.port}

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${blog-gateway.service-url.defaultZone}